#!/usr/bin/env bash
html_name=Edmiston-MERI-2016.html
pdf_name=Edmiston-MERI-2016.pdf
target=$html_name

revealjs=reveal.js
decktape=decktape-1.0.0
cache=.cache
figs=figs

open_after=false
save_as_pdf=false

function make_slides {
	# rmarkdown to markdown
	Rscript -e "knitr::knit('presentation.Rmd', 'presentation.md')"

	# markdown to html
	pandoc -o $revealjs/index.html \
		-t revealjs --section-divs -V theme="simple" \
		-c static/style.css -H static/font.html \
		presentation.md

	if [ ! -e "$html_name" ] ; then
		ln -s $revealjs/index.html $html_name
	fi
}

while getopts ":cfpo" opt; do
		case "$opt" in
				c)
						rm -rf $cache
						;;
				f)
						rm -rf $figs
						;;
				p)
						save_as_pdf=true
						;;
				o)
						open_after=true
						;;
				\?)
						echo "Invalid option: -$OPTARG" >&2
						;;
		esac
done

make_slides

if [ "$save_as_pdf" == true ] ; then
	./phantomjs $decktape/decktape.js \
		reveal file://`pwd`/$html_name $pdf_name
	target=$pdf_name
fi

if [ "$open_after" = true ] ; then
	open "$target"
fi
